export const mockUsersData = [
    { id: 1, 
      email: 'exaple1@gamil.com', 
      password: 'password1',
      tel : '+709999001',
      user: 'Александрова Татьяна Владимировна',
      status: 'Client',
      createDate : '01.01.2020',
      updateDate : ''
    },
    { id: 2, 
      email: 'exaple2@gamil.com',
      password: 'password2',
      tel : '+709999002',
      user: 'Захаров Максим Михайлович', 
      status: 'Partner',
      createDate : '01.01.2020',
      updateDate : '',
    },
    { id: 3, 
      email: 'exaple3@gamil.com',
      password: 'password3',
      tel : '+709999003',
      user: 'Калинкин Андрей Николаевич', 
      status: 'Admin',
      createDate : '01.01.2020',
      updateDate : '',
    }
  ]
  